services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2fbBZeTS9e2hEluxC3r56TMRDNK_7XxMqvDsFuTWy7T1GpGFD
      - USER=$(whoami)
    command:
      - "http"
      - "http://front_end"
    volumes:
      - ./ngrok:/etc:rw
    ports:
      - 4040:4040
    depends_on:
      - front_end
    networks:
      - intra_net
  app:
    image: long/le_app:latest
    container_name: le_app
    env_file:
      - app/.env
    ports:
      - 8000:8000
    volumes:
      - ./app/vocabs:/app/vocabs:rw

    networks:
      - intra_net
  front_end:
    image: long/le_front_end:latest
    container_name: le_front_end
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./frontend:/usr/share/nginx/html:rw
    networks:
      - intra_net
    depends_on:
      - app
networks:
  intra_net:
    driver: bridge
